config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'students/index'

  resources :cohorts
  devise_for :students, :controllers => {:registration => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :votes ,only: [:create, :index]

  get '/students', to: 'students#index'
  get '/students/:id', to: 'students#show', as: 'student'


    get '/admins/students/new', to: 'admins#student_new', as: 'new_student'
  post '/admins/students/new', to: 'admins#student_create', as:'create_student'
  get '/admins/students/:id/edit', to: 'admins#student_edit', as: 'edit_student'
  patch '/admins/students/:id', to: 'admins#student_update', as: 'update_student'
  put '/admins/students/:id', to: 'admins#student_update'

  resources :rounds
  resources :admins
  resources :pitches
  resources :teams

  get '/' => 'static_pages#home'
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <div class="d-flex flex-row">
  <div class="field p-2">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field p-2">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email%>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit "Submit Changes" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h2 class="bg-faded">Edit Admin</h2>
<hr>
<%= render 'form' %>

app/views/admins/index.html.erb
<h1 class="bg-faded">Welcome, <%= current_admin.full_name %></h1>
<hr>
<div class="cohorts">
<div class="btn-group">
  <%= button_to 'New Cohort', new_cohort_path, method: :get, form_class: 'btn btn-secondary' %>
  <%= button_to 'New Student', new_student_path, method: :get, form_class: 'btn btn-secondary' %>
  <%= button_to 'New Admin', new_admin_path, method: :get, form_class: 'btn btn-secondary' %>
  <%= button_to 'List Admins', admin_path(1), method: :get, form_class: 'btn btn-secondary' %>
</div>
  <hr>
  <strong class="bg-faded">Active Cohorts</strong>
  <ul class="list-group">
  <% @cohorts.each do |cohort| %>
    <% if cohort.active %>
      <li class="list-group-item bg-faded"><%= link_to cohort.name, cohort_path(cohort.id) %>&nbsp;(<%= link_to 'Pitch List', rounds_path %>)</li>
    <% end %>
  <% end %>
  </ul>
</div>

<div class="students">
  <% @cohorts.each do |cohort| %>
    <% if cohort.active %>
      <hr>
      <strong><%= cohort.name %> Students:</strong>
      <hr>
      <ul class="list-group">
      <% cohort.students.each do |student| %>
        <li class="list-group-item"><%= link_to student.full_name, edit_student_path(student) %></li>
      <% end %>
      </ul>
    <% end %>
  <% end %>
</div>
<br>

app/views/admins/new.html.erb
<h2 class="bg-faded">Create Admin</h2>
<hr>

<%= render 'form' %>

app/views/admins/pitches.html.erb
<% @cohorts.each do |cohort| %>
<h1><%= cohort.name %></h1>
  <%= form_tag("/rounds/new", method: "get") do %>
  <p>Stage: <%= cohort.stage_id %></p>
  <p>Pitch Due: <%= cohort.pitch_start %></p>
  <p>Voting Due: <%= cohort.vote_end %></p>
  <h3>All Pitches</h3>
  <ol>
    <% cohort.pitches.each do |pitch| %>
      <li><%= link_to pitch.name, pitch_path(pitch), target: :_blank %> - <%= pitch.votes.count %> - <%= check_box_tag(pitch.id) %></li>
    <% end %>
  </ol>
  <%= select_tag(:round_status, options_for_select([['Next Round', 1], ['Create Teams', 2]])) %>
  <%= hidden_field_tag(:cohort_id, cohort.id) %>
  <%= submit_tag('Submit') %>
  <% end %>
<hr>
<% end %>

app/views/admins/show.html.erb
<h1 class="bg-faded">Admins</h1>
<hr>
<ul class="list-group">
<% @admins.each do |admin| %>
<li class="list-group-item bg-faded"><%= link_to admin.full_name, edit_admin_path(admin) %></li>
<% end %>
</ul>