config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'students/index'

  resources :cohorts
  devise_for :students, :controllers => {:registration => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :votes ,only: [:create, :index]

  get '/students', to: 'students#index'
  get '/students/:id', to: 'students#show', as: 'student'


    get '/admins/students/new', to: 'admins#student_new', as: 'new_student'
  post '/admins/students/new', to: 'admins#student_create', as:'create_student'
  get '/admins/students/:id/edit', to: 'admins#student_edit', as: 'edit_student'
  patch '/admins/students/:id', to: 'admins#student_update', as: 'update_student'
  put '/admins/students/:id', to: 'admins#student_update'

  resources :rounds
  resources :admins
  resources :pitches
  resources :teams

  get '/' => 'static_pages#home'
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort
  has_many :pitches
  has_many :votes
  belongs_to :team, optional: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def round_votes(round, vote_level)
    self.votes.select do |vote|
      vote.round_id == round && vote.vote == vote_level
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!
  def index
    if current_student 
    	if current_student.votes.count != current_student.cohort.vote_limit
  	    @cohort = current_student.cohort
  	    @student = Student.find(current_student.id)
  	    @current_pitches = current_student.cohort.pitches
  	    @student_pitches = current_student.pitches
      else
  			redirect_to votes_path
  		end
    else
      redirect_to new_student_session_path
    end
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<h2 class="bg-faded">Update Student</h2>
<hr>

<%= form_for(@student, as: :student, url: update_student_path) do |f| %>
  <div class="d-flex flex-row">
  <div class="field p-2">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field p-2">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email%>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :cohort %><br>
    <%= f.select(:cohort_id) do %>
      <% Cohort.all.each do |c| %>
        <%= content_tag(:option, c.name, value: c.id) %>
      <% end %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/students/index.html.erb
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li class="bg-warning text-black"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h1 class="bg-faded">
Welcome <%=  current_student.full_name %>
</h1>

<% if current_student.cohort.stage_id == 0 %>
  <h2>Pitches due date:
  <%= current_student.cohort.pitch_start %> </h2>
<% elsif current_student.cohort.stage_id == 1  %>
  <h2>Voting due date:
  <%= current_student.cohort.vote_end %> </h2>
<% end %>
<hr>
<% if current_student %>
  <%= render "./pitches/index.html.erb" %>
<% end %>

<% if current_student && current_student.cohort.stage_id >= 1 %>
  <%= render "./votes/vote.html.erb" %>
<% end %>

app/views/students/new.html.erb
<h2 class="bg-faded">Create Student</h2>
<hr>

<%= form_for(@student, as: :student, url: create_student_path) do |f| %>
  <div class="d-flex flex-row">
  <div class="field p-2">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field p-2">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email%>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :cohort %><br>
    <%= f.select(:cohort_id) do %>
      <% Cohort.all.each do |c| %>
        <%= content_tag(:option, c.name, value: c.id) %>
      <% end %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/students/show.html.erb
<br>
<br>
<br>
<p>Name: <%= @student.full_name %></p>
<p>Cohort: <%= @student.cohort.name %></p>