config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'students/index'

  resources :cohorts
  devise_for :students, :controllers => {:registration => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :votes ,only: [:create, :index]

  get '/students', to: 'students#index'
  get '/students/:id', to: 'students#show', as: 'student'


    get '/admins/students/new', to: 'admins#student_new', as: 'new_student'
  post '/admins/students/new', to: 'admins#student_create', as:'create_student'
  get '/admins/students/:id/edit', to: 'admins#student_edit', as: 'edit_student'
  patch '/admins/students/:id', to: 'admins#student_update', as: 'update_student'
  put '/admins/students/:id', to: 'admins#student_update'

  resources :rounds
  resources :admins
  resources :pitches
  resources :teams

  get '/' => 'static_pages#home'
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  validate :name
  validate :description
  validate :student_id
  validate :validate_pitches


  def validate_pitches
      s=Student.find(self.student_id)
      pl=s.cohort.pitch_limit
      if s.pitches.count > (pl - 1)
        errors.add(:pitches,"pitch limit(#{pl}) exceeded for #{s.full_name}")
      end
  end


  belongs_to :student
  has_one :cohort, through: :student
  # validates_associated :cohort
  # belongs_to :cohort, foreign_key: :student_id
  has_many :votes
  belongs_to :team, optional: true

  def round_votes(round, vote_level)
    votes = self.votes.select do |vote|
      vote.round_id == round && vote.vote == vote_level
    end
    votes.count
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  def index
    @pitches = Pitch.all.sort_by(&:updated_at).reverse
  end

  def create
    @pitch = Pitch.create(pitch_params)
    if @pitch.save
      redirect_to "/students/index"
    else
      @errors = ["Error saving"]
      render 'new'
    end
  end

  def new
  end

  def edit
    @pitch = Pitch.find(params[:id])
  end

  def show
    @pitch = Pitch.find(params[:id])
  end

  def update
    @pitch = Pitch.find(params[:id])
     if @pitch.update_attributes(pitch_params)
      flash[:success] = "Pitch updated"
      redirect_to pitch_path(@pitch.id)
    else
      render 'edit'
    end
  end

  def destroy
    @pitch = Pitch.find(params[:id])
    @pitch.destroy
    #later this is home
    redirect_to "/students/index"
  end

private
  def pitch_params
    params.require(:pitch).permit(:name, :description, :student_id)
  end

end

app/views/pitches/_index.html.erb
<!-- Before votting header -->
<% if current_student.cohort.stage_id == 0 %>
  <h2>List of Project Pitches</h2>
  <% if current_student.cohort.pitch_limit > current_student.pitches.count %>
    <%= link_to("New Pitch", new_pitch_path) %> <br>
  <% end %>
<!-- votting header -->
<% elsif current_student.cohort.stage_id >= 1 %>
  <h2>Promoted Pitches</h2>
<% end %>


<!-- Changes just in round 0 -->
<% if current_student.cohort.stage_id == 0 %>
  <% if @student_pitches %>
    <% @student_pitches.each_with_index do |pitch, index| %>
    <%= link_to("#{ index + 1 }. #{pitch.name}", pitch_path(pitch.id))%> 
    <%=  link_to("edit", edit_pitch_path(pitch.id)) %> <%= link_to("delete", pitch_path(pitch.id) , method: "delete") %> 
    <br>
    <hr>
    <% end %>
  <% end %>
<% elsif current_student.cohort.stage_id > 0 %>
  <% if @current_pitches %>
   <% @current_pitches.each_with_index do |pitch, index| %>
      <%= link_to("#{ index + 1 }. #{pitch.name}", pitch_path(pitch.id))%><br> 
    <% end %>
  <% end %>
<% end %>
  

app/views/pitches/edit.html.erb
<h1 class="update-pitch h1-pitches">Update Pitch</h1>

  <% if @errors %>
    <%= @errors.first %>
  <% end %>
  <div class="row">
  <div class="new-pitch col-lg-6">
    <%= form_for :pitch, url: "/pitches/#{@pitch.id}", method: "patch"  do |f|%>
    
    <%= f.hidden_field :student_id, :value => current_student.id%>

      <div class="form-group col-lg-12">
        <label for="name">Name: </label>
        <%= f.text_field :name, :class => "form-control "%><br>
      </div>
      <div class="form-group col-lg-12">
        <label for="description">Description (Accepts md style)</label><br>
        <%= f.text_area :description, rows:12, :class => "form-control form-text-in" %><br>
      </div>
      <div class="form-group col-lg-8 offset-md-5">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>
<!-- THIS IS MD PREVIEW -->
<div class="md-pitch col-lg-6">
  <p>Preview</p>
    <div class="html"></div>
  </div>
</div>

app/views/pitches/new.html.erb
<h1 class="h1-pitches bg-faded">Create a new pitch</h1>
<% if !@pitch.nil? && @pitch.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @pitch.errors.full_messages.each do |msg| %>
          <li class="bg-warning text-black"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="new-pitch col-lg-6">
    <%= form_for :pitch, url: "/pitches" do |f|%>

        <%= f.hidden_field :student_id, :value => current_student.id%>

        <div class="form-group col-lg-12">
          <label for="name">Name:</label>
          <%= f.text_field :name, :class => "form-control "%><br>
        </div>
        <div class="form-group col-lg-12">
          <label for="description">Description (Accepts md style)</label><br>
          <%= f.text_area :description, rows:12, :class => "form-control form-text-in" %><br>
        </div>
        <div class="form-group col-lg-8 offset-md-5">
          <%= f.submit :class => "btn btn-primary" %>
        </div>
    <% end %>
  </div>
  <!-- THIS IS MD PREVIEW -->
  <div class="md-pitch col-lg-6">
    <p>Preview</p>
    <div class="html md-preview"></div>
  </div>
</div>

app/views/pitches/show.html.erb
<!-- Just edit in round 0  -->


Pitch name: <%= @pitch.name %><% if current_student.cohort.stage_id == 0 %>
    <%= link_to("edit", edit_pitch_path(@pitch.id)) %> <br>
  <% end %>
<div class="show-text-in hidden">
  <%= @pitch.description %> 
  
</div>

<div class="html"> </div>